#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: autogen
# autospec version: v3
# autospec commit: fae1327
#
# Source0 file verified with key 0xF434A1EFAFEEAEA3 (build@documentfoundation.org)
#
Name     : libreoffice
Version  : 24.2.0.3
Release  : 113
URL      : https://download.documentfoundation.org/libreoffice/src/24.2.0/libreoffice-24.2.0.3.tar.xz
Source0  : https://download.documentfoundation.org/libreoffice/src/24.2.0/libreoffice-24.2.0.3.tar.xz
Source1  : https://dev-www.libreoffice.org/src/dtoa-20180411.tgz
Source2  : https://dev-www.libreoffice.org/src/skia-m111-a31e897fb3dcbc96b2b40999751611d029bf5404.tar.xz
Source3  : https://download.documentfoundation.org/libreoffice/src/24.2.0/libreoffice-dictionaries-24.2.0.3.tar.xz
Source4  : https://download.documentfoundation.org/libreoffice/src/24.2.0/libreoffice-help-24.2.0.3.tar.xz
Source5  : https://download.documentfoundation.org/libreoffice/src/24.2.0/libreoffice-translations-24.2.0.3.tar.xz
Source6  : https://download.documentfoundation.org/libreoffice/src/24.2.0/libreoffice-24.2.0.3.tar.xz.asc
Summary  : %productname desktop integration
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause BSD-3-Clause CC-BY-SA-3.0 GPL-2.0 GPL-3.0 LGPL-2.0 LGPL-2.1 LGPL-3.0 MPL-1.1 MPL-2.0 MPL-2.0-no-copyleft-exception W3C
BuildRequires : apache-ant
BuildRequires : apr-dev
BuildRequires : bison
BuildRequires : bluez-dev
BuildRequires : boost-dev
BuildRequires : box2d-dev
BuildRequires : bzip2-dev
BuildRequires : clucene-core-dev
BuildRequires : coinmp-dev
BuildRequires : cups-dev
BuildRequires : curl-dev
BuildRequires : doxygen
BuildRequires : dragonbox-dev
BuildRequires : e2fsprogs-dev
BuildRequires : epm
BuildRequires : fakeroot
BuildRequires : flex
BuildRequires : fontforge
BuildRequires : gdb
BuildRequires : glm-dev
BuildRequires : gnupg
BuildRequires : gnutls-dev
BuildRequires : gobject-introspection-dev
BuildRequires : gperf
BuildRequires : gpgme-dev
BuildRequires : hyphen-dev
BuildRequires : icu4c-dev
BuildRequires : krb5-dev
BuildRequires : libabw-dev
BuildRequires : libcdr-dev
BuildRequires : libcmis-dev
BuildRequires : libcuckoo-dev
BuildRequires : libe-book-dev
BuildRequires : libepubgen-dev
BuildRequires : libetonyek-dev
BuildRequires : libfixmath-staticdev
BuildRequires : libfreehand-dev
BuildRequires : libgpg-error-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : liblangtag-dev
BuildRequires : libmspub-dev
BuildRequires : libmwaw-dev
BuildRequires : libodfgen-dev
BuildRequires : liborcus-dev
BuildRequires : libpagemaker-dev
BuildRequires : libqxp-dev
BuildRequires : librevenge-dev
BuildRequires : libstaroffice-dev
BuildRequires : libvisio-dev
BuildRequires : libwpd-dev
BuildRequires : libwpg-dev
BuildRequires : libwps-dev
BuildRequires : libzmf-dev
BuildRequires : mariadb-dev
BuildRequires : mdds-dev
BuildRequires : mythes-dev
BuildRequires : nasm
BuildRequires : nspr-dev
BuildRequires : nss-dev
BuildRequires : openjdk
BuildRequires : openjdk-dev
BuildRequires : openldap-dev
BuildRequires : openssl-dev
BuildRequires : pkgconfig(apr-util-1)
BuildRequires : pkgconfig(atk)
BuildRequires : pkgconfig(atspi-2)
BuildRequires : pkgconfig(cairo)
BuildRequires : pkgconfig(cppunit)
BuildRequires : pkgconfig(dbus-1)
BuildRequires : pkgconfig(dconf)
BuildRequires : pkgconfig(freetype2)
BuildRequires : pkgconfig(gdk-3.0)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gmodule-no-export-2.0)
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : pkgconfig(gstreamer-1.0)
BuildRequires : pkgconfig(gstreamer-pbutils-1.0)
BuildRequires : pkgconfig(gstreamer-plugins-base-1.0)
BuildRequires : pkgconfig(gstreamer-video-1.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(gtk+-unix-print-3.0)
BuildRequires : pkgconfig(gtk4)
BuildRequires : pkgconfig(hunspell)
BuildRequires : pkgconfig(ice)
BuildRequires : pkgconfig(lcms2)
BuildRequires : pkgconfig(libexslt)
BuildRequires : pkgconfig(libexttextcat)
BuildRequires : pkgconfig(libnumbertext)
BuildRequires : pkgconfig(libopenjp2)
BuildRequires : pkgconfig(libpq)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(libxslt)
BuildRequires : pkgconfig(poppler)
BuildRequires : pkgconfig(poppler-cpp)
BuildRequires : pkgconfig(raptor2)
BuildRequires : pkgconfig(redland)
BuildRequires : pkgconfig(sane-backends)
BuildRequires : pkgconfig(sm)
BuildRequires : pkgconfig(xcb)
BuildRequires : pkgconfig(xmlsec1-nss)
BuildRequires : pkgconfig(xrandr)
BuildRequires : pkgconfig(xrender)
BuildRequires : poppler-dev
BuildRequires : postgresql-dev
BuildRequires : pypi-lxml
BuildRequires : python3-dev
BuildRequires : serf-dev
BuildRequires : ucpp
BuildRequires : unixODBC-dev
BuildRequires : valgrind
BuildRequires : vlc-dev
BuildRequires : zxing-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Do-not-clean-destdir.patch
Patch2: 0002-Find-whatever-version-of-dragonbox.patch
Patch3: 0003-Guard-use-of-jfw_convertUserPathList-when-we-don-t-h.patch

%description
a dummy package

%prep
%setup -q -n libreoffice-24.2.0.3
cd %{_builddir}
tar xf %{_sourcedir}/libreoffice-dictionaries-24.2.0.3.tar.xz
cd %{_builddir}
tar xf %{_sourcedir}/libreoffice-help-24.2.0.3.tar.xz
cd %{_builddir}
tar xf %{_sourcedir}/libreoffice-translations-24.2.0.3.tar.xz
cd %{_builddir}
mkdir -p dtoa-20180411
cd dtoa-20180411
tar xf %{_sourcedir}/dtoa-20180411.tgz
cd %{_builddir}
mkdir -p skia-m111-a31e897fb3dcbc96b2b40999751611d029bf5404.tar
cd skia-m111-a31e897fb3dcbc96b2b40999751611d029bf5404.tar
tar xf %{_sourcedir}/skia-m111-a31e897fb3dcbc96b2b40999751611d029bf5404.tar.xz
cd %{_builddir}/libreoffice-24.2.0.3
%patch -P 1 -p1
%patch -P 2 -p1
%patch -P 3 -p1

%build
## build_prepend content
mkdir -p $(echo %{_builddir}/libreoffice-*/external)/tarballs/
cp %{_sourcedir}/dtoa-*.tgz %{_builddir}/libreoffice-*/external/tarballs/
cp %{_sourcedir}/skia-*.tar.xz %{_builddir}/libreoffice-*/external/tarballs/
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1706716141
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
%autogen --disable-static --without-java \
--disable-fetch-external \
--with-system-boost \
--with-system-curl \
--with-system-bluez \
--with-system-zlib \
--with-system-gpgmepp \
--with-system-icu \
--with-system-libs \
--with-system-librevenge \
--with-system-libodfgen \
--with-system-libepubgen \
--with-system-libvisio \
--with-system-libwpd \
--with-system-libwpg \
--with-system-libwps \
--with-system-libcdr \
--with-system-libmspub \
--with-system-libmwaw \
--with-system-libetonyek \
--with-system-libfreehand \
--with-system-libebook \
--with-system-libabw \
--with-system-libpagemaker \
--with-system-libqxp \
--with-system-libzmf \
--with-system-libstaroffice \
--with-system-libcmis \
--without-system-neon \
--with-system-serf \
--disable-neon \
--without-system-firebird \
--without-system-libtommath \
--without-system-hsqldb \
--disable-lpsolve \
--disable-pdfium \
--disable-avahi \
--disable-firebird-sdbc \
--without-fonts \
--with-system-ucpp \
--with-system-postgresql \
--disable-postgresql-sdbc \
--with-vendor="Clear Linux OS for Intel Architecture" \
--enable-build-opensymbol \
--enable-release-build \
--with-myspell-dicts \
--with-help \
--with-lang=ALL \
--with-system-qrcodegen
make  %{?_smp_mflags}  MAKECMDGOALS=build build

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1706716141
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libreoffice
cp %{_builddir}/libreoffice-%{version}/COPYING %{buildroot}/usr/share/package-licenses/libreoffice/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
cp %{_builddir}/libreoffice-%{version}/COPYING.LGPL %{buildroot}/usr/share/package-licenses/libreoffice/e7d563f52bf5295e6dba1d67ac23e9f6a160fab9 || :
cp %{_builddir}/libreoffice-%{version}/COPYING.MPL %{buildroot}/usr/share/package-licenses/libreoffice/d22157abc0fc0b4ae96380c09528e23cf77290a9 || :
cp %{_builddir}/libreoffice-%{version}/bin/text_cat/COPYING %{buildroot}/usr/share/package-licenses/libreoffice/caeb68c46fa36651acf592771d09de7937926bb3 || :
cp %{_builddir}/libreoffice-%{version}/bin/text_cat/Copyright %{buildroot}/usr/share/package-licenses/libreoffice/a2987fb2ef11c7c38cd03bc5d0be22014b63f777 || :
cp %{_builddir}/libreoffice-%{version}/desktop/source/deployment/gui/license_dialog.cxx %{buildroot}/usr/share/package-licenses/libreoffice/95cb917e61a51e152476a289e3e09b6f1d50b35e || :
cp %{_builddir}/libreoffice-%{version}/desktop/source/deployment/gui/license_dialog.hxx %{buildroot}/usr/share/package-licenses/libreoffice/fc52bdd52dcd28fcb258701ff22dc2958c735b1b || :
cp %{_builddir}/libreoffice-%{version}/dictionaries/an_ES/LICENSES-en.txt %{buildroot}/usr/share/package-licenses/libreoffice/981a819a0c9c4a4025d0c52b2b196b124f975d22 || :
cp %{_builddir}/libreoffice-%{version}/dictionaries/ar/COPYING.txt %{buildroot}/usr/share/package-licenses/libreoffice/2f203961eeb312e8253537e3b32b106fd968e45a || :
cp %{_builddir}/libreoffice-%{version}/dictionaries/bg_BG/COPYING %{buildroot}/usr/share/package-licenses/libreoffice/a5ddbc9cb6373c0bbd63da31d0190a3ed9f30fa4 || :
cp %{_builddir}/libreoffice-%{version}/dictionaries/bn_BD/COPYING %{buildroot}/usr/share/package-licenses/libreoffice/0b184ad51ba2a79e85d2288d5fcf8a1ea0481ea4 || :
cp %{_builddir}/libreoffice-%{version}/dictionaries/br_FR/LICENSES-en.txt %{buildroot}/usr/share/package-licenses/libreoffice/f9021477f3ffe66b806c98da42d1328fafee45fb || :
cp %{_builddir}/libreoffice-%{version}/dictionaries/de/COPYING_GPLv2 %{buildroot}/usr/share/package-licenses/libreoffice/ffafa3d581babbe799b390d4d7057d07a6dda4b2 || :
cp %{_builddir}/libreoffice-%{version}/dictionaries/de/COPYING_GPLv3 %{buildroot}/usr/share/package-licenses/libreoffice/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
cp %{_builddir}/libreoffice-%{version}/dictionaries/de/COPYING_LGPL_v2.0.txt %{buildroot}/usr/share/package-licenses/libreoffice/ba8966e2473a9969bdcab3dc82274c817cfd98a1 || :
cp %{_builddir}/libreoffice-%{version}/dictionaries/de/COPYING_LGPL_v2.1.txt %{buildroot}/usr/share/package-licenses/libreoffice/01a6b4bf79aca9b556822601186afab86e8c4fbf || :
cp %{_builddir}/libreoffice-%{version}/dictionaries/de/COPYING_OASIS.txt %{buildroot}/usr/share/package-licenses/libreoffice/26f94fe5a890afb135cc9fea45fdcef51c4439aa || :
cp %{_builddir}/libreoffice-%{version}/dictionaries/en/WordNet_license.txt %{buildroot}/usr/share/package-licenses/libreoffice/ffdb86b8f5a1a5020288c7fcc996258f44bf691d || :
cp %{_builddir}/libreoffice-%{version}/dictionaries/en/license.txt %{buildroot}/usr/share/package-licenses/libreoffice/086522998bce7aa9e5a07c02b0336895c8940a4d || :
cp %{_builddir}/libreoffice-%{version}/dictionaries/eo/license-en.txt %{buildroot}/usr/share/package-licenses/libreoffice/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
cp %{_builddir}/libreoffice-%{version}/dictionaries/fa_IR/LICENSE %{buildroot}/usr/share/package-licenses/libreoffice/2d916b125f26702c55ecd1a7aba6bf62dffb19e0 || :
cp %{_builddir}/libreoffice-%{version}/dictionaries/gd_GB/LICENSES-en.txt %{buildroot}/usr/share/package-licenses/libreoffice/f5dce21518ec83c44e57f084f494634ff53ddc14 || :
cp %{_builddir}/libreoffice-%{version}/dictionaries/gl/COPYING_th_gl %{buildroot}/usr/share/package-licenses/libreoffice/73a5c65a9ad1edb175e9e3b28db6b2612abb467b || :
cp %{_builddir}/libreoffice-%{version}/dictionaries/hi_IN/COPYING %{buildroot}/usr/share/package-licenses/libreoffice/0b184ad51ba2a79e85d2288d5fcf8a1ea0481ea4 || :
cp %{_builddir}/libreoffice-%{version}/dictionaries/hi_IN/Copyright %{buildroot}/usr/share/package-licenses/libreoffice/1e1ed49217c54335ff1a9c391094166d4dfe5fff || :
cp %{_builddir}/libreoffice-%{version}/dictionaries/id/LICENSE-dict %{buildroot}/usr/share/package-licenses/libreoffice/49d4c0ce1a16601f1e265d446b6c5ea6b512f27c || :
cp %{_builddir}/libreoffice-%{version}/dictionaries/id/LICENSE-thes %{buildroot}/usr/share/package-licenses/libreoffice/5919d75f19b76bef533d4ff10d3cca634752aaec || :
cp %{_builddir}/libreoffice-%{version}/dictionaries/is/license.txt %{buildroot}/usr/share/package-licenses/libreoffice/c20a43e2449b367c09f9e5f665febc631e99848a || :
cp %{_builddir}/libreoffice-%{version}/dictionaries/it_IT/legacy/it_IT_license.txt %{buildroot}/usr/share/package-licenses/libreoffice/a9d9e3aae241e2506e0c9ef63f26fbcffe1209e2 || :
cp %{_builddir}/libreoffice-%{version}/dictionaries/kmr_Latn/license.txt %{buildroot}/usr/share/package-licenses/libreoffice/1efe32a14d6ac9af625ba23a893352d02de30add || :
cp %{_builddir}/libreoffice-%{version}/dictionaries/lt_LT/COPYING %{buildroot}/usr/share/package-licenses/libreoffice/865dcd10722390043968e224401709450c0bbb54 || :
cp %{_builddir}/libreoffice-%{version}/dictionaries/lv_LV/license.txt %{buildroot}/usr/share/package-licenses/libreoffice/720ac006232639ed551ce48d638dee35f8d378d4 || :
cp %{_builddir}/libreoffice-%{version}/dictionaries/no/COPYING %{buildroot}/usr/share/package-licenses/libreoffice/ffafa3d581babbe799b390d4d7057d07a6dda4b2 || :
cp %{_builddir}/libreoffice-%{version}/dictionaries/pt_BR/license-thes.readme %{buildroot}/usr/share/package-licenses/libreoffice/cd4d2be2fb45653d8f8923933046f5a4cb4ff882 || :
cp %{_builddir}/libreoffice-%{version}/dictionaries/pt_PT/LICENSES.txt %{buildroot}/usr/share/package-licenses/libreoffice/552e717402633ecd4b29e48ff5c293ff6baca7bd || :
cp %{_builddir}/libreoffice-%{version}/dictionaries/ro/COPYING.GPL %{buildroot}/usr/share/package-licenses/libreoffice/0c4fabaa9f307652fd2b2f0057b8048809cca570 || :
cp %{_builddir}/libreoffice-%{version}/dictionaries/ro/COPYING.LGPL %{buildroot}/usr/share/package-licenses/libreoffice/cf756914ec51f52f9c121be247bfda232dc6afd2 || :
cp %{_builddir}/libreoffice-%{version}/dictionaries/ro/COPYING.MPL %{buildroot}/usr/share/package-licenses/libreoffice/aba8d76d0af67d57da3c3c321caa59f3d242386b || :
cp %{_builddir}/libreoffice-%{version}/dictionaries/si_LK/LICENSES-en.txt %{buildroot}/usr/share/package-licenses/libreoffice/98da77a33f378a25b9ab4b40dfdb4af8bdd4919f || :
cp %{_builddir}/libreoffice-%{version}/dictionaries/sk_SK/LICENSE.txt %{buildroot}/usr/share/package-licenses/libreoffice/cb3b074e16ba14585901215392dae8054260b960 || :
cp %{_builddir}/libreoffice-%{version}/dictionaries/sv_SE/LICENSE_en_US.txt %{buildroot}/usr/share/package-licenses/libreoffice/3d6124299beadbdf34e46a1af82771afa1216a17 || :
cp %{_builddir}/libreoffice-%{version}/dictionaries/sv_SE/LICENSE_sv_SE.txt %{buildroot}/usr/share/package-licenses/libreoffice/9da09717e40fd46206f0e48ad32cb3e6e0c425d3 || :
cp %{_builddir}/libreoffice-%{version}/dictionaries/tr_TR/COPYING.MPL %{buildroot}/usr/share/package-licenses/libreoffice/d22157abc0fc0b4ae96380c09528e23cf77290a9 || :
cp %{_builddir}/libreoffice-%{version}/dictionaries/tr_TR/LICENSE %{buildroot}/usr/share/package-licenses/libreoffice/d22157abc0fc0b4ae96380c09528e23cf77290a9 || :
cp %{_builddir}/libreoffice-%{version}/dictionaries/vi/LICENSES-en.txt %{buildroot}/usr/share/package-licenses/libreoffice/cea402c4f150370f47b5f5e7ef461df23ec6a04d || :
cp %{_builddir}/libreoffice-%{version}/dictionaries/vi/LICENSES-vi.txt %{buildroot}/usr/share/package-licenses/libreoffice/75b80fb33eafe0831107b9b6f5bd7306e4b1ca46 || :
cp %{_builddir}/libreoffice-%{version}/extras/source/autocorr/lang/hr/licence.md %{buildroot}/usr/share/package-licenses/libreoffice/dfa4d68ffb8c478209adb3ff777f33d0853d364d || :
cp %{_builddir}/libreoffice-%{version}/icon-themes/breeze/COPYING %{buildroot}/usr/share/package-licenses/libreoffice/b6d50f880188b674c13931fdeb12d6c7c454ca4d || :
cp %{_builddir}/libreoffice-%{version}/icon-themes/breeze_dark/COPYING %{buildroot}/usr/share/package-licenses/libreoffice/b6d50f880188b674c13931fdeb12d6c7c454ca4d || :
cp %{_builddir}/libreoffice-%{version}/icon-themes/breeze_dark_svg/COPYING %{buildroot}/usr/share/package-licenses/libreoffice/b6d50f880188b674c13931fdeb12d6c7c454ca4d || :
cp %{_builddir}/libreoffice-%{version}/icon-themes/breeze_svg/COPYING %{buildroot}/usr/share/package-licenses/libreoffice/b6d50f880188b674c13931fdeb12d6c7c454ca4d || :
cp %{_builddir}/libreoffice-%{version}/icon-themes/elementary/LICENSE.GPL %{buildroot}/usr/share/package-licenses/libreoffice/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
cp %{_builddir}/libreoffice-%{version}/icon-themes/elementary_svg/LICENSE.GPL %{buildroot}/usr/share/package-licenses/libreoffice/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
cp %{_builddir}/libreoffice-%{version}/icon-themes/karasa_jaga/COPYING %{buildroot}/usr/share/package-licenses/libreoffice/f635d28c6cbaac2760d09920ba63f19ed1ef6a27 || :
cp %{_builddir}/libreoffice-%{version}/icon-themes/karasa_jaga/LICENSE %{buildroot}/usr/share/package-licenses/libreoffice/49d4c0ce1a16601f1e265d446b6c5ea6b512f27c || :
cp %{_builddir}/libreoffice-%{version}/icon-themes/karasa_jaga_svg/COPYING %{buildroot}/usr/share/package-licenses/libreoffice/f635d28c6cbaac2760d09920ba63f19ed1ef6a27 || :
cp %{_builddir}/libreoffice-%{version}/icon-themes/karasa_jaga_svg/LICENSE %{buildroot}/usr/share/package-licenses/libreoffice/49d4c0ce1a16601f1e265d446b6c5ea6b512f27c || :
cp %{_builddir}/libreoffice-%{version}/icon-themes/sifr/LICENSE %{buildroot}/usr/share/package-licenses/libreoffice/c8da430cb95f9242128698ef24b1cdd1fa195b13 || :
cp %{_builddir}/libreoffice-%{version}/icon-themes/sifr_dark/LICENSE %{buildroot}/usr/share/package-licenses/libreoffice/c8da430cb95f9242128698ef24b1cdd1fa195b13 || :
cp %{_builddir}/libreoffice-%{version}/icon-themes/sifr_dark_svg/LICENSE %{buildroot}/usr/share/package-licenses/libreoffice/c8da430cb95f9242128698ef24b1cdd1fa195b13 || :
cp %{_builddir}/libreoffice-%{version}/icon-themes/sifr_svg/LICENSE %{buildroot}/usr/share/package-licenses/libreoffice/c8da430cb95f9242128698ef24b1cdd1fa195b13 || :
cp %{_builddir}/libreoffice-%{version}/icon-themes/sukapura/LICENSE %{buildroot}/usr/share/package-licenses/libreoffice/e18ea3c11db626436e9ca66acdb93aa2242ea90b || :
cp %{_builddir}/libreoffice-%{version}/icon-themes/sukapura_dark/LICENSE %{buildroot}/usr/share/package-licenses/libreoffice/e18ea3c11db626436e9ca66acdb93aa2242ea90b || :
cp %{_builddir}/libreoffice-%{version}/icon-themes/sukapura_dark_svg/LICENSE %{buildroot}/usr/share/package-licenses/libreoffice/e18ea3c11db626436e9ca66acdb93aa2242ea90b || :
cp %{_builddir}/libreoffice-%{version}/icon-themes/sukapura_svg/LICENSE %{buildroot}/usr/share/package-licenses/libreoffice/e18ea3c11db626436e9ca66acdb93aa2242ea90b || :
cp %{_builddir}/libreoffice-%{version}/odk/examples/DevelopersGuide/Components/SimpleLicense/LicenseTest.idl %{buildroot}/usr/share/package-licenses/libreoffice/b84cab96fef495a36ca31fc11e714c0a16a758a6 || :
cp %{_builddir}/libreoffice-%{version}/odk/examples/DevelopersGuide/Components/SimpleLicense/LicenseTest.java %{buildroot}/usr/share/package-licenses/libreoffice/a76a0e7e8a8c7f46a328c16110f3c1dfbf9196ad || :
cp %{_builddir}/libreoffice-%{version}/offapi/com/sun/star/deployment/LicenseException.idl %{buildroot}/usr/share/package-licenses/libreoffice/0750f8a342c58c97c14c2f30a7d14f5c13c88f11 || :
cp %{_builddir}/libreoffice-%{version}/offapi/com/sun/star/deployment/ui/LicenseDialog.idl %{buildroot}/usr/share/package-licenses/libreoffice/572b30719f1bd06cb821ab3e3c2660073ed0a744 || :
cp %{_builddir}/libreoffice-%{version}/sfx2/uiconfig/ui/licensedialog.ui %{buildroot}/usr/share/package-licenses/libreoffice/0169a4be13bb4c785992df830ac21a8df2116c8f || :
%make_install distro-pack-install
## Remove excluded files
rm -f %{buildroot}*/usr/lib64/libreoffice/sdk/classes
rm -f %{buildroot}*/usr/lib64/libreoffice/sdk/docs
rm -f %{buildroot}*/usr/lib64/libreoffice/sdk/include
rm -f %{buildroot}*/usr/lib64/libreoffice/sdk/index.html

%files
%defattr(-,root,root,-)
